version: '3'

services:
  mongodb:
    image: 'mongo:5'
    container_name: 'mongodb'
    ports:
      - "27017:27017"


  mongo_express:
    image: mongo-express
    container_name: 'mongo-express'
    depends_on:
      - mongodb
    links:
      - mongodb
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb